ftruncate: : No such process
[2019-12-13 15:09:52] INFO  (logfile_rotation_job) : log file rotation job done
[2019-12-13 15:09:52] INFO  (main) Starting MEA-EDOMUS 0.0-lite
{
	"MEAPATH":	"/Users/patrice/Developpement/Logiciels/mea-edomus-lite/demo",
	"HTML_PATH":	"./html",
	"LOGPATH":	"/Users/patrice/Developpement/Logiciels/mea-edomus-lite/demo/var/log",
	"PLUGINPATH":	"/Users/patrice/Developpement/Logiciels/mea-edomus-lite/demo/lib/mea-plugins",
	"DRIVERSPATH":	"/Users/patrice/Developpement/Logiciels/mea-edomus-lite/build/Debug",
	"XPL_VENDORID":	"mea",
	"XPL_DEVICEID":	"edomus",
	"XPL_INSTANCEID":	"demo",
	"VERBOSELEVEL":	"1",
	"HTTP_PORT":	"8083",
	"INTERFACE":	"en0",
	"RULESFILE":	"/Users/patrice/Developpement/Logiciels/mea-edomus-lite/demo/lib/mea-rules/automator.rules",
	"USERSFILE":	"users.json",
	"RULESFILESPATH":	"/Users/patrice/Developpement/Logiciels/mea-edomus-lite/demo/lib/mea-rules"
}
DATATIMESERVER : c62000
MAIN : 196dc0
[2019-12-13 15:09:52] INFO  (_timeServer_thread) : Traitement jour
start(0) : 08:35
end(0) :  16:53
start(1) : 07:58
end(1) :  17:30
[2019-12-13 15:09:52] INFO  (start_httpServer) : GUISERVER launched successfully.
PYTHONPLUGINSERVER : 26fe000
[2019-12-13 15:09:52] INFO  (start_pythonPluginServer) : PYTHONPLUGINSERVER launched successfully.
[2019-12-13 15:09:53] INFO  (start_xPLServer) : XPLSERVER launched successfully.
AUTOMATORSERVER : 2804000
[2019-12-13 15:09:53] INFO  (start_automatorServer) : AUTOMATORSERVER launched successfully.
INPUTS TABLE :
--------------
rule STARTUP: (string)N/A (6)
rule NOW: (string)N/A (6)
rule FILTRE1: (string)N/A (6)
rule FILTRE2: (string)N/A (6)
rule FILTRE3: (string)N/A (6)
rule FILTRE4: (string)N/A (6)
rule I1: (string)N/A (6)
rule NEXT: (string)N/A (6)
rule O1: (string)N/A (6)
rule TIMER1: (string)N/A (6)
--------------
[2019-12-13 15:09:53] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 54010
[2019-12-13 15:09:53] ERROR (start_interface_type_003) : enocean_init - Unable to open serial port (/dev/tty.usbserial-FTY1A5FM).
[2019-12-13 15:09:53] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:09:53] ERROR (start_interface_type_002) : init_xbee - Unable to open serial port (/dev/ttyUSB1).
[2019-12-13 15:09:53] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
FREE start_interface_type_002 1476
[2019-12-13 15:09:53] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:09:53] INFO  (start_interface_type_010) : I010 launched successfully.
[[2019-12-13 15:09:53] INFO  (main) : MEA-EDOMUS 0.0-lite starded
2019-12-13 15:09:53] INFO  (mea_init) - lancement mea_init
[2019-12-13 15:09:53] DEBUG (mea_call_python_function2) : Result of call : 1
[2019-12-13 15:09:53] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:09:58] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:09:58] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:10:00] INFO  (_timeServer_thread) : Traitement minute
[2019-12-13 15:10:03] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:10:03] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:10:08] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:10:08] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:10:20] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:10:34] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:10:34] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:10:34] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:10:34] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:10:34] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:10:34] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:11:08] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:11:08] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:11:08] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:11:08] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:11:08] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:11:08] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 60149
[2019-12-13 15:11:08] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:11:08] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:11:08] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:11:25] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:11:34] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:12:07] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:12:07] INFO  (automator_timerCtrl) : start timer timer1
[2019-12-13 15:12:09] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:12:59] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:12:59] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:12:59] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:12:59] INFO  (_automator_thread) : timer wakeup signal
[2019-12-13 15:13:11] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:13:11] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:13:11] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:13:11] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:13:11] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 52220
[2019-12-13 15:13:11] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:13:11] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:13:11] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:13:16] INFO  (xPLServer_thread) : XPLSERVER thread is running
[2019-12-13 15:13:42] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:13:42] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:13:42] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:13:42] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:13:42] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:13:42] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:13:42] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:13:42] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:13:42] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 59651
[2019-12-13 15:13:42] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:13:42] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:13:42] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:13:47] INFO  (xPLServer_thread) : XPLSERVER thread is running
[2019-12-13 15:14:27] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:14:30] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:14:38] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:14:38] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:14:38] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:14:38] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:14:38] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:14:38] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:14:38] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 62767
[2019-12-13 15:14:38] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:14:38] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:14:38] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:15:00] INFO  (_timeServer_thread) : Traitement minute
[2019-12-13 15:15:05] INFO  (xPLServer_thread) : XPLSERVER thread is running
[2019-12-13 15:15:09] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:15:09] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:15:09] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:15:09] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:15:09] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:15:09] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:15:09] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:15:09] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:15:09] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 57984
[2019-12-13 15:15:09] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:15:09] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:15:09] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:15:36] INFO  (xPLServer_thread) : XPLSERVER thread is running
[2019-12-13 15:15:40] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:15:40] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:15:40] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:15:40] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:15:40] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:15:40] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:15:40] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:15:40] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:15:40] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 55393
[2019-12-13 15:15:40] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:15:40] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:15:40] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:16:00] INFO  (_timeServer_thread) : Traitement minute
[2019-12-13 15:16:07] INFO  (xPLServer_thread) : XPLSERVER thread is running
[2019-12-13 15:16:11] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:16:11] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:16:11] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:16:11] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:16:11] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:16:11] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:16:11] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:16:11] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:16:11] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 49565
[2019-12-13 15:16:11] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:16:11] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:16:11] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:16:38] INFO  (xPLServer_thread) : XPLSERVER thread is running
[2019-12-13 15:16:42] ERROR (xPLServer_thread) : no xPL message since 30 seconds, but we should have one ... I send me three or more !
[2019-12-13 15:16:42] ERROR (xPLServer_thread) : watchdog_recovery forced ...
[2019-12-13 15:16:42] INFO  (_managed_processes_processes_check_heartbeats) : watchdog process for XPLSERVER
[2019-12-13 15:16:42] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery started for XPLSERVER
[2019-12-13 15:16:42] DEBUG (stop_xPLServer) : XPLSERVER, end after 2 loop(s)
[2019-12-13 15:16:42] INFO  (stop_xPLServer) : XPLSERVER stopped successfully.
[2019-12-13 15:16:42] INFO  (start_xPLServer) : XPLSERVER launched successfully.
[2019-12-13 15:16:42] INFO  (_managed_processes_processes_check_heartbeats) : watchdog recovery done for XPLSERVER (ret=0)
[2019-12-13 15:16:42] INFO  (mea_xPLConnectHub) : xPL Starting in Hub mode on port 49468
[2019-12-13 15:16:42] INFO  (mea_xPLConnectBroadcast) : auto-assigning IP address of 172.16.15.4
[2019-12-13 15:16:42] DEBUG (mea_xPLConnectBroadcast) : NETMASK=feffff
[2019-12-13 15:16:42] ERROR (mea_xPLConnectBroadcast) : assigned xPL Broadcast address of 172.16.15.255, port 3865
[2019-12-13 15:17:01] INFO  (logfile_rotation_job) : log file rotation job start
